#!/bin/bash

echo "========================================="
echo "🎉 服务已经在运行！"
echo "========================================="
echo ""
echo "当前可访问的地址："
echo ""
echo "  Hub API: http://localhost:38080"
echo "  Web UI:  http://localhost:3000"
echo ""
echo "健康检查："
echo -n "  API状态: "
curl -sf http://localhost:38080/health > /dev/null && echo "✓ 正常" || echo "✗ 异常"
echo ""
echo "默认登录凭证："
echo "  用户名: admin"
echo "  密码: admin123"
echo ""
echo "========================================="
echo ""
echo "如需修复端口为8080，请运行："
echo "  ./quick-fix.sh"
echo ""
echo "或者更新部署脚本以检查38080端口："
echo "  将deploy.sh中的8080改为38080"